config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :properties, only: [:show,:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    validates :title,:description,:rooms,:bathroom,:daily_rate, presence: {message:'não pode ficar em branco'}

  
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController<ApplicationController
  def index
    @properties = Property.all()
  end
end

app/controllers/properties_controller.rb
class PropertiesController<ApplicationController
  def show
    id = params[:id]
    @property = Property.find(id)
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.create(params.require(:property).permit(:title,:description,:rooms,:parking_slot,:bathroom,:pets,:daily_rate))
    if @property.save 
      redirect_to @property
    else
      # render :new ==> renderisa a tela new, e não redireciona
      render :new
      # redirect_to new_property_path
    end 
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Flats</h1>
<h3>Boas vindas ao sistema de locação de apartamentos</h3>


<% if @properties.empty? %>
  <div><span>Nenhum imóvel disponível</span></div>
<% end %>
<% @properties.each do |p| %>
  <%= link_to(p.title, property_path(p.id)) %>
  <%= p.description %>
  Quartos: <%= p.rooms %>
<% end %>

<%= link_to 'Cadastrar Imóvel', new_property_path %>

app/views/properties/new.html.erb
<h1>Cadastrar Imóvel</h1>

<% if @property.errors.any? %>
    <ul>
        <% @property.errors.full_messages.each do |error| %>
            <li> <%= error %> </li>
        <% end %>    
    </ul>
<% end %>
<%= form_with(model: @property) do |f| %>
    <div>
        <%= f.label :title, 'Título'%>
        <%= f.text_field :title %>    
    </div>

     <div>
        <%= f.label :description, 'Descrição'%>
        <%= f.text_field :description %>    
    </div>

    <div>
        <%= f.label :rooms, 'Quartos'%>
        <%= f.text_field :rooms %>    
    </div>

    <div>
        <%= f.label :bathroom, 'Banheiros'%>
        <%= f.text_field :bathroom %>    
    </div>

    <div>
        <%= f.label :daily_rate, 'Diária'%>
        <%= f.text_field :daily_rate %>    
    </div>

    <div>
        <%= f.label :pets, 'Aceita Pets'%>
        <%= f.check_box :pets %>    
    </div>

    <div>
        <%= f.label :parking_slot, 'Vaga de Estacionamento'%>
        <%= f.check_box :parking_slot %>    
    </div>

    <%= f.submit 'Enviar' %>
<% end %>

app/views/properties/show.html.erb
<div>
    <h1>
        <%= @property.title%>
    </h1>
    <h2>
        <%= @property.description%>
    </h2>
    <dl>
        <dt>Quartos:</dt>
        <dd><%= @property.rooms%></dd>
        <dt>Banheiros:</dt>
        <%# lembrar de coloar bathrooms no pural %>
        <dd><%= @property.bathroom %></dd>
       
        <dt>Aceita Pets:</dt>
        <% if @property.pets? %>
            <dd>Sim</dd>
        <% else %>
            <dd>Não</dd>
        <% end %>

        <dt>Estacionamento: </dt>
        <% if @property.parking_slot? %>
            <dd>Sim</dd>
        <% else %>
            <dd>Não</dd>
        <% end %>
        
        <dt>Diária:</dt>
        <dd><%= number_to_currency(@property.daily_rate, unit: 'R$', separator:',' , format:"%u %n") %></dd>
    </dl>
    <%= link_to('Voltar', root_path) %>
</div>